import type { ReactNode } from 'react';
import { ArrowRight, ArrowUpRight, Bell, CalendarDays, ChevronRight, Clock3, MapPin, ShieldCheck } from 'lucide-react';
import { MLink } from './layout';
import { PortalIcon } from './visuals';
import type { SchoolEvent } from './events';

type Props={role:'parent'|'teacher'|'admin';pupil:{name:string;class:string;school:string;id:string};menus:string[][];events:SchoolEvent[];read:boolean;children:ReactNode};
export function PortalDashboard({role,pupil,menus,events,read,children}:Props){
  const upcoming=events.filter(e=>e.campus==='All schools'||e.campus===pupil.school).slice().sort((a,b)=>a.date.localeCompare(b.date)).slice(0,2);
  const parent=role==='parent',admin=role==='admin';
  return <>
    <div className="m-portal-welcome"><div><p className="m-eyebrow">{parent?'PARENT & GUARDIAN WORKSPACE':admin?'SCHOOL ADMINISTRATION':'TEACHER WORKSPACE'}</p><h1>{parent?'Your family’s school update.':admin?'School overview.':'Your class, at a glance.'}</h1><p>{parent?'Results, school updates and the things to prepare for at home.':admin?'Applications, records and updates ready for your attention.':'Record absences when needed, update scores and prepare lessons.'}</p></div><span className="m-demo-pill"><ShieldCheck size={14}/>DEMO WORKSPACE</span></div>
    <section className="m-pupil-banner"><span className="m-pupil-avatar">{parent?pupil.name.split(' ').map(w=>w[0]).join(''):admin?'SA':'MA'}</span><div><small>{parent?'SELECTED SAMPLE CHILD':admin?'SAMPLE SCHOOL ACCOUNT':'SAMPLE TEACHER ACCOUNT'}</small><h2>{parent?pupil.name:admin?'School Admin':'Mr. Ahmed'}</h2><p>{parent?`${pupil.class} · ${pupil.school}`:admin?'MIMS Schools · Administration':'JSS 2 · Class teacher'}</p></div><div className="m-pupil-term"><CalendarDays size={20}/><span>First term<small>Fictional school records</small></span></div>{parent&&<MLink page="portal/parent/profile" aria-label="Open family profile"><ChevronRight size={23}/></MLink>}</section>
    {children}
    <div className="m-panel-title m-actions-heading"><h2><PortalIcon name="dashboard" size={21}/>What would you like to do?</h2><span>Your school shortcuts</span></div>
    <div className="m-workspace-actions">{menus.filter(([,s])=>s!=='dashboard'&&s!=='profile'&&s!=='timetable').map(([t,s])=><MLink key={s} page={`portal/${role}/${s}`}><span className={`m-workspace-icon m-workspace-${s}`}><PortalIcon name={s} size={27}/></span><strong>{t}</strong><ArrowUpRight size={17}/></MLink>)}</div>
    <div className="m-dashboard-grid"><section className="m-panel"><div className="m-panel-title"><h2><Clock3 size={21}/>{admin?'Review queue':'Today’s learning'}</h2><MLink page={`portal/${role}/${admin?'admissions':'timetable'}`}>View all<ArrowUpRight size={16}/></MLink></div>{(admin?[['Application review','Amina Hassan · JSS 1'],['Content review','School community update'],['Fee statement','Six sample fee records']]:[['08:00','Assembly & Islamic learning'],['09:00','Mathematics · Fractions'],['10:30','English · Descriptive writing'],['12:00','Basic Science · Practical lesson']]).map(([t,d])=><div className="m-agenda-row" key={t}><span>{t}</span><p>{d}</p></div>)}</section>
      <section className="m-panel m-notice-summary"><div className="m-panel-title"><h2><Bell size={21}/>School notices</h2><span className="m-status">{read?'Read':'2 new'}</span></div><div className="m-dashboard-notice"><span className="m-notice-dot"/><div><small>SAMPLE NOTICE</small><h3>Parent–teacher meeting</h3><p>A conversation about your child’s progress.</p></div></div><div className="m-dashboard-notice"><span className="m-notice-dot"/><div><small>SAMPLE NOTICE</small><h3>Preparing for next week</h3><p>Learning materials and homework reminders.</p></div></div><MLink page={`portal/${role}/notices`} className="m-text-link">Read school updates<ArrowRight size={17}/></MLink></section></div>
    {parent&&<section className="m-panel m-dashboard-events"><div className="m-panel-title"><h2><CalendarDays size={21}/>Coming up at school</h2><MLink page="portal/parent/events">All upcoming events<ArrowUpRight size={16}/></MLink></div><p className="m-note">Sample events for {pupil.school}. Dates are for this preview only.</p><div className="m-upcoming-grid">{upcoming.map(e=><MLink key={e.id} page="portal/parent/events" className="m-upcoming-card"><span className="m-mini-date"><strong>{e.date.slice(8)}</strong><small>{new Intl.DateTimeFormat('en-GB',{month:'short',timeZone:'UTC'}).format(new Date(`${e.date}T12:00:00Z`))}</small></span><div><small>{e.category}</small><h3>{e.title}</h3><p><MapPin size={13}/>{e.location}</p><span><Clock3 size={13}/>{e.time}</span></div><ArrowUpRight size={17}/></MLink>)}</div></section>}
  </>;
}
