export const asset = (name: string) => `/mims-assets/${name}.jpg`;
export const groups = [
  { title: 'About', page: 'about', links: [['Our story','about'],['Chairman’s welcome','about/welcome'],['History & milestones','about/history'],['Mission & vision','about/mission-vision'],['Leadership','about/leadership']] },
  { title: 'Our schools', page: 'schools', links: [['All five schools','schools'],['An-Nur, Bariga','schools/an-nur'],['Primary, Bajulaiye','schools/bajulaiye'],['Primary, Surulere','schools/surulere'],['College, Somolu','schools/somolu'],['College, Epe','schools/epe']] },
  { title: 'Learning', page: 'academics', links: [['Academics & curriculum','academics'],['Learning facilities','facilities'],['School life','school-life'],['Photo gallery','gallery']] },
  { title: 'Admissions', page: 'admissions', links: [['Join MIMS','admissions'],['Application preview','admissions/apply'],['Entrance assessment','admissions/entrance-examination'],['Parent questions','faq']] },
  { title: 'Community', page: 'news', links: [['News & achievements','news'],['Our alumni','alumni'],['Contact & visits','contact']] },
];
export const schools = [
  { id:'an-nur', name:'An-Nur Nursery & Primary School', place:'Bariga', level:'Nursery & Primary', address:'10 Adeshina Street, Bariga, Lagos', phones:['08027597940','08134950563'], image:'campus', intro:'A joyful beginning, with room to discover.', detail:'Children learn through hands-on activities, role play, Montessori and play-based methods. Literacy, numeracy and Islamic learning grow alongside curiosity and confidence.', events:['Prize Giving Day, 2024','Colour Day & Cultural Day, 2024','UNILAG Faculty of Science field trip, 2023','LEAMSP debate recognition, 2026'] },
  { id:'bajulaiye', name:'MIMS Nursery & Primary School', place:'Bajulaiye, Somolu', level:'Nursery & Primary', address:'7 Fatomi Crescent, Bajulaiye, Somolu, Lagos', phones:['08026196269','08035964046','08143541385'], image:'award', intro:'Strong foundations for the years ahead.', detail:'The Bajulaiye school brings academic learning, character development and Islamic values together. Its published introduction welcomes children aged 3–10; the admissions team can advise on the right entry class.', events:['LEAMSP competition achievements','Primary school graduation','Literacy, numeracy & practical learning'] },
  { id:'surulere', name:'MIMS Nursery & Primary School', place:'Surulere', level:'Nursery & Primary', address:'1 Gbaja Market Flat, opposite Gbaja Girls High School, Surulere, Lagos', phones:['08082041952','08029751502'], image:'school-life', intro:'Nurturing the whole child.', detail:'The Surulere school focuses on children’s educational, moral, physical and spiritual development. Learning extends beyond lessons through celebrations, excursions and friendly competition.', events:['Prize Giving Day & Shodex Garden visit, 2024','World Hijab Day & Cultural Day, 2024','Handwriting Day & Colour Day, 2024','NTA 10 educative TV show recognition, 2020','Airport excursion, 2022','Nigerian Railway Corporation visit, 2019'] },
  { id:'somolu', name:'MIMS Comprehensive College', place:'Somolu', level:'Secondary', address:'7 Akinrinlo Street, Bajulaiye, Somolu, Lagos', phones:['08134303430','08024664469','08061684008'], image:'hero-original', intro:'Preparing confident, capable young people.', detail:'A broad Western and Islamic education helps students develop self-confidence, independence and academic ambition. Science, humanities and business pathways are supported by practical work and activities outside the classroom.', events:['UNILAG / UNICEF Resource Challenge winner, 2024','Prestige National Award & LEAMSP wins, 2024','AEI competition third runner-up, 2024','LAMATA Blue Line & Mr. Fish Place visits, 2024','LIQC competition achievement, 2022','Obasanjo Presidential Library excursion, 2022','Press Club with Bond FM guest, 2022','Young Managers Club Day, 2022','C-Way, Agbara & Egbin power station visits, 2019'] },
  { id:'epe', name:'MIMS Comprehensive College', place:'Epe', level:'Secondary', address:'Contact the school for the current Epe campus address and visiting directions.', phones:['08023330011'], image:'debate', intro:'Learning with purpose. Growing in confidence.', detail:'MCC Epe shares the group’s commitment to a rounded education, academic growth and self-reliance. The school’s public introduction emphasises raising role models through a holistic programme.', events:['Egbin power station excursion, 2019','Academic and Islamic learning','Practical experiences beyond the classroom'] },
];
export const stories = [
  {id:'an-nur-debate',title:'Young voices. A remarkable achievement.',category:'Achievement',date:'2026',image:'campus',summary:'An-Nur pupils received LEAMSP recognition following success in the 2026 debate competition.',body:'The school reports that An-Nur won the Somolu zonal debate event before joining MIMS Primary and Caramot Schools to represent the zone at state level. Recognition followed at the Somolu 1448AH Hijrah Awareness Programme. The achievement celebrates pupils’ preparation, speaking skills and teamwork.'},
  {id:'state-champions',title:'MIMS celebrates LEAMSP state champions',category:'Achievement',date:'2026',image:'award',summary:'The college and primary school were recognised after their performances in the LEAMSP Triathlon.',body:'According to MIMS’ published report, the schools earned first positions at zonal and state levels in the 2026 LEAMSP Triathlon Competition. The recognition was presented at the Somolu Hijrah Awareness Programme in Yaba. Teachers, pupils and parents shared in the celebration.'},
  {id:'hamnah-law',title:'From An-Nur to a future in law',category:'Alumni',date:'School spotlight',image:'champions',summary:'Murtada Hamnah Olaoluwa’s journey continues at Bayero University, Kano.',body:'Hamnah completed primary education at An-Nur in 2019 before progressing to MIMS Comprehensive College. The school’s alumni spotlight reports her admission to Common and Sharia Law at Bayero University, Kano. Her story connects the early years of learning with a new chapter in higher education.',noPortrait:true},
  {id:'thirty-years',title:'Thirty years, one school community',category:'Events',date:'8 April 2025',image:'sports',summary:'Five school communities came together for the ninth biennial inter-house sports and anniversary celebration.',body:'The celebration took place at Yabatech Sports Complex. Green, Yellow, Blue and Purple Houses participated in march past, track and field events, with football and table tennis activities in the lead-up. The occasion marked the group’s 30th anniversary and brought pupils, families and staff together.'},
  {id:'practical-learning',title:'Learning you can put into practice',category:'Learning',date:'School life',image:'practical',summary:'Senior students explore catering through practical preparation and presentation.',body:'The school’s published catering showcase features SS2 students preparing traditional dishes, rice, salads and baked food. Practical lessons connect classroom knowledge with preparation, teamwork and everyday skills.'},
  {id:'quiz-2025',title:'A strong showing at the state quiz',category:'Achievement',date:'2025',image:'hero-original',summary:'MCC students celebrated a state quiz win, with the primary team also recognised.',body:'MIMS’ report names Hajarah Bello and Fatimah Adelopo in the college’s winning team. Primary pupils AbdulRahmon Ajayi and Ridwan Shoyiga also represented the school and placed fifth. These achievements are part of the school’s published competition archive.'},
  {id:'school-statement',title:'A statement from the board on school safety',category:'Statements',date:'10 July 2026',image:'debate',summary:'The school published a board statement on the reported rescue of pupils and teachers in Oyo State.',body:'The statement, signed by Board Chairman Prince Adesegun Ogungbayi, expressed support for school safety initiatives and sympathy for affected families. This preview summarises MIMS’ institutional statement; it does not independently verify the events described.'},
  {id:'achievements-archive',title:'The achievements archive',category:'Achievement',date:'2023–2024',image:'award',summary:'Competition highlights from the school’s recent archive.',body:'The current website records a 2023 Spelldemic win and a 324 JAMB score, alongside 2024 achievements in AEI, the UNILAG / UNICEF Resource Challenge, the Prestige National Award and LEAMSP competitions. These reports are presented as school-published achievements.'},
];
export const gallery = [
  {image:'award',title:'Celebrating our pupils',category:'Achievements'},
  {image:'campus',title:'A proud school moment',category:'Achievements'},
  {image:'hero-original',title:'Learning and recognition',category:'Achievements'},
  {image:'school-life',title:'Out and about together',category:'School life'},
  {image:'practical',title:'Catering in practice',category:'Learning'},
  {image:'sports',title:'Thirty years of community',category:'Events'},
  {image:'debate',title:'Recognition across our schools',category:'Achievements'},
  {image:'champions',title:'Celebrating individual success',category:'Achievements'},
];
export const faqs = [
  ['Which school should I apply to?','There are three nursery and primary locations—Bariga, Bajulaiye and Surulere—and two secondary locations—Somolu and Epe. Contact your preferred branch to confirm the entry class and available places.'],
  ['How do admissions work?','The published process begins with registration, followed by an assessment and communication from the school. A successful applicant receives an admission offer and instructions for completing registration. This preview’s application is a demonstration only.'],
  ['When is the next entrance examination?','The website describes entrance examinations during the third term and supplementary assessments. Exact dates and the current admission session must be confirmed with the school.'],
  ['What are the application fees?','The existing website publishes ₦3,500 for primary and ₦7,000 for secondary registration. These figures may have changed. Confirm current fees directly before making any payment. No payments are accepted in this preview.'],
  ['What do students learn?','The school combines Western and Islamic education. Programmes include literacy and numeracy, sciences, humanities and business subjects, alongside Qur’an, Arabic and Islamic studies. Subjects depend on level and branch.'],
  ['Can I visit a campus?','Contact the relevant branch to arrange a visit. The visit request here demonstrates how a future booking form could work; it does not send a request to the school.'],
  ['Is the portal connected to student records?','No. This is a proposed portal with fictional pupil records, staff, teacher-recorded absences, results and fee amounts. The school’s existing portal remains a separate system.'],
];
export const milestones = [['1995','A small beginning','The group’s history begins with six children at Istijabah Mosque in Somolu.'],['1996','Early years education','The nursery and primary school’s introduction records its foundation in 1996.'],['1999','Growing into Surulere','The school expanded to Surulere as its community grew.'],['2000','MIMS Comprehensive College','The secondary school was established, extending the educational journey.'],['2008','Examination approvals','The school records WAEC and NECO approval for the college.'],['2025','Thirty years together','The anniversary was celebrated alongside the ninth biennial inter-house sports.']];
