import { useState } from 'react';
import { CalendarDays, Check, MapPin } from 'lucide-react';
export type SchoolEvent = { id: string; title: string; date: string; time: string; campus: string; location: string; category: string; detail: string };
export const sampleEvents: SchoolEvent[] = [
  {id:'meeting',title:'Parent–teacher meeting',date:'2026-11-05',time:'10:00',campus:'All schools',location:'Your child’s campus',category:'Meetings',detail:'A sample opportunity for parents to discuss learning and progress with class teachers.'},
  {id:'culture',title:'School cultural day',date:'2026-11-12',time:'09:00',campus:'MIMS Bajulaiye',location:'School grounds',category:'Activities',detail:'A sample school celebration. Confirm any preparations and parent participation with the school.'},
  {id:'revision',title:'Term assessment briefing for parents',date:'2026-11-20',time:'15:00',campus:'MCC Somolu',location:'College assembly space',category:'Academic',detail:'A sample briefing about assessment preparations and supporting learning at home.'},
];
const campuses=['All schools','MCC Somolu','MIMS Bajulaiye','An-Nur Bariga','MIMS Surulere','MCC Epe'];
export function SchoolEvents({admin,campus,events,onSave}:{admin:boolean;campus:string;events:SchoolEvent[];onSave:(event:SchoolEvent)=>void}){
  const [category,setCategory]=useState('All events'),[editing,setEditing]=useState<string|null>(null);
  const visible=events.filter(e=>(admin||e.campus==='All schools'||e.campus===campus)&&(category==='All events'||category===e.category)).slice().sort((a,b)=>a.date.localeCompare(b.date));
  const edited=events.find(e=>e.id===editing);
  return <>
    <div className="m-demo-note">SAMPLE UPCOMING EVENTS · All dates, times and arrangements here are fictional. No real school event is announced by this preview.</div>
    <div className="m-panel"><p className="m-eyebrow">PLAN AHEAD, STAY CONNECTED</p><h2>{admin?'Manage school events':'Upcoming school events'}</h2><p>{admin?'Add a sample event for every school or a specific campus. Parents would see events that apply to their child.':`Events for ${campus} and the wider MIMS community. Parents can see what is coming up without children needing to use the portal.`}</p><div className="m-filters">{['All events','Meetings','Activities','Academic'].map(c=><button key={c} className={category===c?'m-selected':''} onClick={()=>setCategory(c)}>{c}</button>)}</div>
      <div className="m-event-list">{visible.length?visible.map(e=>{const [year,month,day]=e.date.split('-');return <article key={e.id}><div className="m-event-date"><strong>{day}</strong><span>{['JAN','FEB','MAR','APR','MAY','JUN','JUL','AUG','SEP','OCT','NOV','DEC'][Number(month)-1]}</span><small>{year}</small></div><div><p className="m-eyebrow">{e.category} · {e.campus}</p><h3>{e.title}</h3><div className="m-event-meta"><span><CalendarDays size={15}/>{day}/{month}/{year} · {e.time||'Time to be confirmed'}</span><span><MapPin size={15}/>{e.location}</span></div><p>{e.detail}</p><span className="m-status m-amber">Illustrative event</span>{admin&&<button className="m-text-link" onClick={()=>setEditing(e.id)}>Edit demo event</button>}</div></article>;}):<p>No sample events match this category for the selected child.</p>}</div>
    </div>
    {admin&&<div className="m-panel"><h2>{edited?'Edit sample event':'Add a sample event'}</h2><form key={editing||'new'} onSubmit={e=>{e.preventDefault();const d=new FormData(e.currentTarget);onSave({id:edited?.id||`demo-${Date.now()}`,title:String(d.get('title')),date:String(d.get('date')),time:String(d.get('time')),campus:String(d.get('campus')),location:String(d.get('location')),category:String(d.get('category')),detail:String(d.get('detail'))});setEditing(null);e.currentTarget.reset();}}><div className="m-form-grid"><label>Event title<input name="title" required maxLength={100} defaultValue={edited?.title||''} placeholder="Sample school event"/></label><label>School<select name="campus" defaultValue={edited?.campus||'All schools'}>{campuses.map(c=><option key={c}>{c}</option>)}</select></label><label>Sample date<input name="date" type="date" required defaultValue={edited?.date||''}/></label><label>Time<input name="time" type="time" defaultValue={edited?.time||''}/></label><label>Location<input name="location" required maxLength={100} defaultValue={edited?.location||''} placeholder="Sample venue"/></label><label>Category<select name="category" defaultValue={edited?.category||'Meetings'}><option>Meetings</option><option>Activities</option><option>Academic</option></select></label></div><label>Event details<textarea name="detail" required maxLength={1000} defaultValue={edited?.detail||''} placeholder="Sample information for parents…"/></label><div className="m-actions"><button className="m-button" type="submit">Save demo event<Check size={16}/></button>{edited&&<button className="m-button m-button-outline" type="button" onClick={()=>setEditing(null)}>Cancel editing</button>}</div><p className="m-note">Demo events remain in this preview session. Nothing is published to the real school website or sent to families.</p></form></div>}
  </>;
}
