import { ArrowRight, ArrowUpRight, BookOpen, CalendarDays, GraduationCap, Heart, History, MapPin, ShieldCheck, Trophy } from 'lucide-react';
import { schools, stories } from './data';
import { ButtonLink, Image, MLink, SectionHeading } from './layout';
import { FeatureIcon, PageIcon } from './visuals';

const shortcuts=[['schools','Find your school','Explore our five Lagos branches'],['admissions','Admissions','Entry classes and how to apply'],['portal','Parent portal','Results, updates and school events'],['news','School news','Achievements and community stories']] as const;

export function HomePreview(){return <>
  <section className="m-new-hero">
    <div className="m-new-hero-copy"><p className="m-eyebrow"><span className="m-dot"/> WESTERN & ISLAMIC EDUCATION · LAGOS</p><h1>Growing up<br/>with <span>MIMS.</span></h1><p>From their first school days to their final college exams. Nursery, primary and secondary education across five Lagos schools.</p><div className="m-actions"><ButtonLink page="schools">Find your school</ButtonLink><MLink page="admissions" className="m-text-link">Explore admissions<ArrowRight size={18}/></MLink></div><div className="m-hero-facts"><span><History size={18}/><strong>Since 1995</strong></span><span><MapPin size={18}/><strong>5 Lagos schools</strong></span><span><GraduationCap size={18}/><strong>Nursery to college</strong></span></div></div>
    <div className="m-photo-mosaic"><MLink page="news/state-champions" className="m-mosaic-main"><Image name="award" alt="MIMS children celebrating with their achievement certificates" priority/><span><Trophy size={20}/><span>Our pupils. Our pride.<small>Explore school achievements</small></span><ArrowUpRight size={20}/></span></MLink><MLink page="school-life" className="m-mosaic-small"><Image name="school-life" alt="MIMS pupils together on a school excursion" priority/><span>Beyond the classroom<ArrowUpRight size={17}/></span></MLink><MLink page="news/an-nur-debate" className="m-mosaic-small m-mosaic-award"><Image name="campus" alt="An-Nur pupils holding their certificates" priority/><span>Young voices, big achievements<ArrowUpRight size={17}/></span></MLink><span className="m-photo-stamp"><ShieldCheck size={24}/><span>Knowledge.<br/>Character. Faith.</span></span></div>
  </section>
  <section className="m-shortcut-strip" aria-label="Explore MIMS">{shortcuts.map(([page,title,detail])=><MLink key={page} page={page}><span className={`m-icon-tile m-tile-${page}`}><PageIcon page={page} size={27}/></span><span><strong>{title}</strong><small>{detail}</small></span><ArrowUpRight size={18}/></MLink>)}</section>
  <section className="m-section m-new-about"><div className="m-about-photo"><Image name="hero-original" alt="MIMS students and school community celebrating an achievement"/><span><History size={22}/><strong>Our story began<br/>with six children.</strong><MLink page="about/history">Read our history<ArrowRight size={16}/></MLink></span></div><div><p className="m-eyebrow">GET TO KNOW MIMS</p><h2>A school day built around<br/>knowledge, character<br/>and faith.</h2><p>MIMS brings Western and Islamic learning together. Our schools serve families in Bariga, Bajulaiye, Surulere, Somolu and Epe, from early years through secondary education.</p><div className="m-value-pills"><span><BookOpen size={19}/>Knowledge</span><span><Heart size={19}/>Character</span><span><ShieldCheck size={19}/>Faith</span></div><MLink page="about" className="m-text-link">Meet our school community<ArrowRight size={18}/></MLink></div></section>
  <section className="m-section m-new-schools"><SectionHeading eyebrow="OUR FIVE SCHOOLS" title="Find the school closest to you." page="schools" link="Compare all schools"/><div className="m-school-visual-grid">{schools.map((s,i)=><article key={s.id}><MLink page={`schools/${s.id}`} className="m-school-visual-photo"><Image name={s.image} alt={`${s.name}: school community photograph`}/><span className="m-school-level"><FeatureIcon name={s.level} size={15}/>{s.level}</span></MLink><div><p className="m-eyebrow"><MapPin size={13}/>{s.place}</p><h3>{s.name}</h3><p>{s.id==='epe'?'Contact the school for campus directions.':s.address}</p><MLink page={`schools/${s.id}`} className="m-school-card-link"><span>Explore school</span><ArrowRight size={18}/></MLink></div><span className="m-school-index">0{i+1}</span></article>)}</div></section>
  <section className="m-section m-new-learning"><div><p className="m-eyebrow">WHAT CHILDREN LEARN</p><h2>In class.<br/>In practice.<br/>In everyday life.</h2><p>Core subjects, Islamic education and practical experiences, with learning that develops as children move through school.</p><div className="m-actions"><ButtonLink page="academics">Explore the curriculum</ButtonLink><MLink page="facilities" className="m-text-link">Learning facilities<ArrowRight size={17}/></MLink></div><Image name="practical" alt="Food prepared during MIMS catering practical lessons"/></div><div className="m-learning-card-grid">{([['Early years','Play, stories and hands-on discovery.','Nursery & primary'],['Science & technology','From classroom ideas to experiments and practical work.','Learning facilities'],['Islamic learning','Qur’an, Arabic, Tahfiz and Islamic studies.','Faith & character'],['Sports & school clubs','Excursions, competitions and activities beyond lessons.','School life']] as const).map(([name,text,tag])=><MLink page={name.includes('Sports')?'school-life':name.includes('Science')?'facilities':'academics'} key={name}><span className="m-icon-tile"><FeatureIcon name={name} size={32}/></span><small>{tag}</small><h3>{name}</h3><p>{text}</p><ArrowUpRight size={19}/></MLink>)}</div></section>
  <section className="m-section m-new-journal"><SectionHeading eyebrow="FROM OUR SCHOOLS" title="The latest from MIMS." page="news" link="All news & achievements"/><div className="m-journal-grid">{[stories[1]!,stories[0]!,stories[3]!].map((s,i)=><article className={i===0?'m-journal-feature':''} key={s.id}><MLink page={`news/${s.id}`}><Image name={s.image} alt={s.title}/></MLink><div><p className="m-eyebrow">{s.category==='Events'?<CalendarDays size={15}/>:<Trophy size={15}/>} {s.category} <span>· {s.date}</span></p><h3><MLink page={`news/${s.id}`}>{s.title}</MLink></h3><p>{s.summary}</p><MLink page={`news/${s.id}`} className="m-text-link">Read story<ArrowRight size={17}/></MLink></div></article>)}</div></section>
  <section className="m-section m-new-life"><SectionHeading eyebrow="LIFE AT MIMS" title="More than lessons." page="school-life" link="Discover school life"/><div className="m-life-grid"><MLink page="gallery"><Image name="school-life" alt="MIMS girls on an excursion"/><span><span><PageIcon page="gallery"/>School days, in pictures</span><ArrowUpRight/></span></MLink><MLink page="news/thirty-years"><Image name="sports" alt="Families and staff at the MIMS anniversary sports celebration"/><span><span><Trophy/>Thirty years together</span><ArrowUpRight/></span></MLink></div><MLink page="alumni" className="m-alumni-banner"><GraduationCap size={34}/><span><strong>Where do MIMS alumni go next?</strong><small>Read stories from the school’s alumni community.</small></span><ArrowRight size={24}/></MLink></section>
</>;}
