import { Link } from '@tanstack/react-router';
import { useEffect, useRef, useState, type ReactNode } from 'react';
import { ArrowUpRight, Search, Menu, X, ArrowRight, ChevronDown, Mail, Phone, MapPin, ShieldCheck } from 'lucide-react';
import { asset, groups, schools, stories } from './data';
import { PageIcon } from './visuals';

export function MLink({ page='', children, className='', onClick, 'aria-label':ariaLabel }: {page?:string|undefined;children:ReactNode;className?:string;onClick?:()=>void;'aria-label'?:string}) {
  return page ? <Link to="/mims/$" params={{_splat:page}} className={className} onClick={onClick} aria-label={ariaLabel}>{children}</Link> : <Link to="/mims" className={className} onClick={onClick} aria-label={ariaLabel}>{children}</Link>;
}
export function ButtonLink({page,children,light=false}:{page:string;children:ReactNode;light?:boolean}) {return <MLink page={page} className={`m-button ${light?'m-button-light':''}`}>{children}<ArrowRight size={17}/></MLink>;}
export function Image({name,alt,className='',priority=false}:{name:string;alt:string;className?:string;priority?:boolean}) {return <img src={asset(name)} alt={alt} className={className} loading={priority?'eager':'lazy'} decoding="async"/>;}
export function Dialog({title,children,onClose}:{title:string;children:ReactNode;onClose:()=>void}) {
  const ref=useRef<HTMLDialogElement>(null);
  useEffect(()=>{const el=ref.current;el?.showModal();return()=>el?.close();},[]);
  return <dialog ref={ref} className="m-dialog" onCancel={onClose} onClick={e=>{if(e.target===e.currentTarget)onClose();}}><div className="m-dialog-top"><h2>{title}</h2><button aria-label="Close dialog" onClick={onClose}><X/></button></div>{children}</dialog>;
}
export function Header({page}:{page:string}) {
  const [menu,setMenu]=useState(false),[search,setSearch]=useState(false),[query,setQuery]=useState('');
  useEffect(()=>{setMenu(false);setSearch(false);},[page]);
  const entries=[['Home',''],...groups.flatMap(g=>g.links),...schools.map(s=>[`${s.name}, ${s.place}`,`schools/${s.id}`]),...stories.map(s=>[s.title,`news/${s.id}`])];
  const results=entries.filter(([label])=>(label||'').toLowerCase().includes(query.toLowerCase())).slice(0,12);
  return <>
    <a href="#m-main" className="m-skip">Skip to content</a>
    <div className="m-preview"><span>DESIGN PREVIEW <i/> MIMS Schools</span><a href="/">By Ibrahim Alli <ArrowUpRight size={12}/></a></div>
    <div className="m-topline"><span><MapPin size={12}/>Five schools across Lagos</span><div><MLink page="contact">Visit a school</MLink><a href="tel:+2348023330011"><Phone size={12}/>0802 333 0011</a></div></div>
    <header className="m-header"><MLink className="m-logo"><Image name="logo" alt="MIMS Educational Resources Limited" priority/></MLink>
      <nav className="m-desktop" aria-label="Main navigation"><MLink className={!page?'m-active':''}>Home</MLink>{groups.map(g=><div className="m-nav-group" key={g.title}><MLink page={g.page} className={page.startsWith(g.page)?'m-active':''}>{g.title}<ChevronDown size={12}/></MLink><div className="m-dropdown"><p className="m-eyebrow">EXPLORE {g.title}</p>{g.links.map(([label,to])=><MLink key={to} page={to}><span className="m-menu-icon"><PageIcon page={to} size={18}/></span><span>{label}</span><ArrowUpRight size={13}/></MLink>)}</div></div>)}</nav>
      <div className="m-header-actions"><button aria-label="Search the website" className="m-search-button" onClick={()=>setSearch(true)}><Search size={19}/></button><MLink page="portal" className="m-portal-link"><ShieldCheck size={17}/>School portal</MLink><button className="m-menu-button" aria-label={menu?'Close navigation':'Open navigation'} aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div>
    </header>
    {menu&&<nav className="m-mobile-nav" aria-label="Mobile navigation"><MLink><PageIcon page=""/>Home</MLink>{groups.map(g=><details key={g.title}><summary><PageIcon page={g.page}/>{g.title}<ChevronDown size={17}/></summary>{g.links.map(([label,to])=><MLink key={to} page={to}><PageIcon page={to} size={17}/>{label}</MLink>)}</details>)}<MLink page="portal"><ShieldCheck size={20}/>School portal</MLink></nav>}
    {search&&<Dialog title="What are you looking for?" onClose={()=>setSearch(false)}><label className="m-search-field"><Search size={20}/><input autoFocus aria-label="Search pages and news" placeholder="A school, admissions, results…" value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="m-search-results">{results.length?results.map(([title,to],i)=><MLink key={`${to}-${i}`} page={to} onClick={()=>setSearch(false)}><PageIcon page={to} size={18}/><span>{title}</span><ArrowUpRight size={17}/></MLink>):<p>No matching pages. Try a school name or “admissions”.</p>}</div></Dialog>}
  </>;
}
export function Footer(){return <><section className="m-join"><Image name="school-life" alt="MIMS pupils at a school outing"/><div><p className="m-eyebrow">LET’S TALK ABOUT YOUR CHILD’S NEXT STEP</p><h2>Come and meet us.</h2><p>Ask about admissions or arrange a visit to your nearest MIMS school.</p><div className="m-actions"><ButtonLink page="admissions" light>Admissions</ButtonLink><ButtonLink page="contact" light>Contact the school</ButtonLink></div></div></section><footer className="m-footer"><div className="m-footer-intro"><Image name="logo" alt="MIMS Schools"/><p>Western & Islamic education.<br/>Nursery, primary & secondary.</p><a href="mailto:mimscomprehensive@gmail.com"><Mail size={16}/>mimscomprehensive@gmail.com</a><a href="tel:+2348023330011"><Phone size={16}/>0802 333 0011</a></div>{groups.map(g=><div key={g.title}><h3><PageIcon page={g.page} size={17}/>{g.title}</h3>{g.links.map(([label,to])=><MLink key={to} page={to}>{label}</MLink>)}</div>)}<div className="m-footer-bottom"><span>© MIMS Educational Resources Limited · Lagos, Nigeria</span><span>Design concept by <a href="/">Ibrahim Alli</a> · Forms & portal use sample data.</span></div></footer></>}
const pageTitles:Record<string,string>={
  'An education with purpose.':'Get to know MIMS.','Welcome to our family.':'A welcome from the Chairman.','Small beginnings. Lasting purpose.':'How MIMS began.','The purpose behind every lesson.':'Our mission & vision.','People who guide our schools.':'Meet our leadership.',
  'Find the right beginning.':'Five schools. Find yours.','A rounded education. A wider world.':'What children learn at MIMS.','Space to explore. Tools to understand.':'Inside our learning spaces.','A new beginning starts with a conversation.':'Joining MIMS.','The next step in their journey.':'Entrance assessments.','Make the first step feel simple.':'Start an application.','A little clarity goes a long way.':'Your questions, answered.','A closer look at school life.':'MIMS in pictures.','Stories worth sharing.':'News from our schools.','The learning doesn’t stop at the classroom door.':'Life beyond lessons.','The next chapter. And the one after that.':'Where our alumni go next.','Let’s start a conversation.':'Contact MIMS.',
};
const heroPhotos:Record<string,string>={'About MIMS':'hero-original','Our schools':'award','Academics & curriculum':'practical','Learning facilities':'practical','Admissions':'campus','Entrance assessment':'award','Application preview':'campus','Parent questions':'hero-original','Photo gallery':'school-life','The MIMS journal':'award','School life':'school-life','Our alumni':'hero-original','Contact & visits':'sports'};
export function PageHero({eyebrow,title,description,image,children}:{eyebrow:string;title:string;description:string;image?:string;children?:ReactNode}) {
  const photo=image||heroPhotos[eyebrow]||'award';
  const route=eyebrow.includes('admission')||eyebrow.includes('Admission')||eyebrow.includes('Application')?'admissions':eyebrow.includes('school')||eyebrow.includes('Primary')||eyebrow.includes('Secondary')?'schools':eyebrow.includes('Academics')?'academics':eyebrow.includes('facilities')?'facilities':eyebrow.includes('gallery')?'gallery':eyebrow.includes('journal')?'news':eyebrow.includes('Contact')?'contact':'about';
  return <section className="m-page-hero m-page-hero-image"><div><div className="m-breadcrumb"><MLink>Home</MLink><span>/</span><span>{eyebrow}</span></div><span className="m-page-symbol"><PageIcon page={route} size={27}/></span><p className="m-eyebrow">{eyebrow}</p><h1>{pageTitles[title]||title}</h1><p className="m-lead">{description}</p>{children}</div><div className="m-page-photo"><Image name={photo} alt={`${eyebrow} at MIMS Schools`} priority/><span><MapPin size={14}/>Our school community · Lagos</span></div></section>;
}
export function SectionHeading({eyebrow,title,page,link='Explore more'}:{eyebrow:string;title:string;page?:string;link?:string}) {return <div className="m-section-heading"><div><p className="m-eyebrow">{page&&<PageIcon page={page} size={16}/>} {eyebrow}</p><h2>{title}</h2></div>{page&&<MLink page={page} className="m-text-link">{link}<ArrowRight size={18}/></MLink>}</div>}
