import { Link } from '@tanstack/react-router';
import { useEffect, useRef, useState, type ReactNode } from 'react';
import { ArrowUpRight, Search, Menu, X, ArrowRight, ChevronDown, Mail, Phone } from 'lucide-react';
import { asset, groups, schools, stories } from './data';

export function MLink({ page='', children, className='', onClick }: {page?:string|undefined;children:ReactNode;className?:string;onClick?:()=>void}) {
  return page ? <Link to="/mims/$" params={{_splat:page}} className={className} onClick={onClick}>{children}</Link> : <Link to="/mims" className={className} onClick={onClick}>{children}</Link>;
}
export function ButtonLink({page,children,light=false}:{page:string;children:ReactNode;light?:boolean}) {return <MLink page={page} className={`m-button ${light?'m-button-light':''}`}>{children}<ArrowUpRight size={17}/></MLink>;}
export function Image({name,alt,className='',priority=false}:{name:string;alt:string;className?:string;priority?:boolean}) {return <img src={asset(name)} alt={alt} className={className} loading={priority?'eager':'lazy'} decoding="async"/>;}
export function Dialog({title,children,onClose}:{title:string;children:ReactNode;onClose:()=>void}) {
  const ref=useRef<HTMLDialogElement>(null);
  useEffect(()=>{const el=ref.current;el?.showModal();return()=>el?.close();},[]);
  return <dialog ref={ref} className="m-dialog" onCancel={onClose} onClick={e=>{if(e.target===e.currentTarget)onClose();}}><div className="m-dialog-top"><h2>{title}</h2><button aria-label="Close dialog" onClick={onClose}><X/></button></div>{children}</dialog>;
}
export function Header({page}:{page:string}) {
  const [menu,setMenu]=useState(false),[search,setSearch]=useState(false),[query,setQuery]=useState('');
  useEffect(()=>{setMenu(false);setSearch(false);},[page]);
  const entries=[['Home',''],...groups.flatMap(g=>g.links),...schools.map(s=>[`${s.name}, ${s.place}`,`schools/${s.id}`]),...stories.map(s=>[s.title,`news/${s.id}`])];
  const results=entries.filter(([label])=>(label||'').toLowerCase().includes(query.toLowerCase())).slice(0,12);
  return <><a href="#m-main" className="m-skip">Skip to content</a><div className="m-preview"><span>DESIGN PREVIEW <i/> MIMS Schools</span><a href="/">A concept by Ibrahim Alli <ArrowUpRight size={12}/></a></div><div className="m-topline"><span>Knowledge. Character. Faith.</span><div><MLink page="contact">Plan a school visit</MLink><a href="tel:+2348023330011">0802 333 0011</a></div></div><header className="m-header"><MLink className="m-logo"><Image name="logo" alt="MIMS Educational Resources Limited" priority/><span>EDUCATIONAL RESOURCES LIMITED</span></MLink><nav className="m-desktop" aria-label="Main navigation">{groups.map(g=><div className="m-nav-group" key={g.title}><MLink page={g.page} className={page.startsWith(g.page)?'m-active':''}>{g.title}<ChevronDown size={12}/></MLink><div className="m-dropdown">{g.links.map(([label,to])=><MLink key={to} page={to}>{label}<ArrowUpRight size={13}/></MLink>)}</div></div>)}</nav><div className="m-header-actions"><button aria-label="Search the website" onClick={()=>setSearch(true)}><Search size={20}/></button><MLink page="portal" className="m-portal-link">School portal<ArrowUpRight size={15}/></MLink><button className="m-menu-button" aria-label={menu?'Close navigation':'Open navigation'} aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div></header>{menu&&<nav className="m-mobile-nav" aria-label="Mobile navigation"><MLink>Home</MLink>{groups.map(g=><details key={g.title}><summary>{g.title}</summary>{g.links.map(([label,to])=><MLink key={to} page={to}>{label}</MLink>)}</details>)}<MLink page="portal">School portal</MLink></nav>}{search&&<Dialog title="Find your way around MIMS" onClose={()=>setSearch(false)}><label className="m-search-field"><Search size={20}/><input autoFocus aria-label="Search pages and news" placeholder="Try admissions, Somolu, curriculum…" value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="m-search-results">{results.length?results.map(([title,to],i)=><MLink key={`${to}-${i}`} page={to} onClick={()=>setSearch(false)}>{title}<ArrowUpRight size={17}/></MLink>):<p>No matching pages. Try a school name or “admissions”.</p>}</div></Dialog>}</>;
}
export function Footer(){return <><section className="m-join"><div><p className="m-eyebrow">THE NEXT CHAPTER STARTS HERE</p><h2>Come and meet<br/>the MIMS family.</h2></div><div><p>Find your nearest school, ask a question or take the first step towards admission.</p><div className="m-actions"><ButtonLink page="admissions" light>Explore admissions</ButtonLink><ButtonLink page="contact" light>Talk to the school</ButtonLink></div></div></section><footer className="m-footer"><div className="m-footer-intro"><Image name="logo" alt="MIMS Schools"/><p>A foundation in knowledge.<br/>A life guided by values.</p><a href="mailto:mimscomprehensive@gmail.com"><Mail size={16}/>mimscomprehensive@gmail.com</a><a href="tel:+2348023330011"><Phone size={16}/>0802 333 0011</a></div>{groups.map(g=><div key={g.title}><h3>{g.title}</h3>{g.links.map(([label,to])=><MLink key={to} page={to}>{label}</MLink>)}</div>)}<div className="m-footer-bottom"><span>© MIMS Educational Resources Limited · Lagos, Nigeria</span><span>Independent design concept by <a href="/">Ibrahim Alli</a>. Forms & portal are demonstrations.</span></div></footer></>}
export function PageHero({eyebrow,title,description,image,children}:{eyebrow:string;title:string;description:string;image?:string;children?:ReactNode}) {return <section className={`m-page-hero ${image?'m-page-hero-image':''}`}><div><div className="m-breadcrumb"><MLink>Home</MLink><span>/</span><span>{eyebrow}</span></div><p className="m-eyebrow">{eyebrow}</p><h1>{title}</h1><p className="m-lead">{description}</p>{children}</div>{image&&<Image name={image} alt={`${eyebrow} at MIMS Schools`} priority/>}</section>}
export function SectionHeading({eyebrow,title,page,link='Explore more'}:{eyebrow:string;title:string;page?:string;link?:string}) {return <div className="m-section-heading"><div><p className="m-eyebrow">{eyebrow}</p><h2>{title}</h2></div>{page&&<MLink page={page} className="m-text-link">{link}<ArrowRight size={18}/></MLink>}</div>}
