/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as DayyahCoutureIndexRouteImport } from './routes/dayyah-couture/index'
import { Route as DayyahCouturePageRouteImport } from './routes/dayyah-couture/$page'
import { Route as ProjectsSlugRouteImport } from './routes/projects/$slug'
import { Route as SafiyyrIndexRouteImport } from './routes/safiyyr/index'
import { Route as SafiyyrShopRouteImport } from './routes/safiyyr/shop'
import { Route as SallysApparelIndexRouteImport } from './routes/sallys-apparel/index'
import { Route as SallysApparelShopRouteImport } from './routes/sallys-apparel/shop'
import { Route as SuperPlusStudiosIndexRouteImport } from './routes/super-plus-studios/index'
import { Route as SuperPlusStudiosCustomRequestRouteImport } from './routes/super-plus-studios/custom-request'
import { Route as SuperPlusStudiosCustomiseRouteImport } from './routes/super-plus-studios/customise'
import { Route as SuperPlusStudiosShopRouteImport } from './routes/super-plus-studios/shop'
import { Route as SuperPlusStudiosTrackRouteImport } from './routes/super-plus-studios/track'
import { Route as SafiyyrProductSlugRouteImport } from './routes/safiyyr/product/$slug'
import { Route as SallysApparelProductSlugRouteImport } from './routes/sallys-apparel/product/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const DayyahCoutureIndexRoute = DayyahCoutureIndexRouteImport.update({
  id: '/dayyah-couture/',
  path: '/dayyah-couture/',
  getParentRoute: () => rootRouteImport,
} as any)
const DayyahCouturePageRoute = DayyahCouturePageRouteImport.update({
  id: '/dayyah-couture/$page',
  path: '/dayyah-couture/$page',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SafiyyrIndexRoute = SafiyyrIndexRouteImport.update({
  id: '/safiyyr/',
  path: '/safiyyr/',
  getParentRoute: () => rootRouteImport,
} as any)
const SafiyyrShopRoute = SafiyyrShopRouteImport.update({
  id: '/safiyyr/shop',
  path: '/safiyyr/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SallysApparelIndexRoute = SallysApparelIndexRouteImport.update({
  id: '/sallys-apparel/',
  path: '/sallys-apparel/',
  getParentRoute: () => rootRouteImport,
} as any)
const SallysApparelShopRoute = SallysApparelShopRouteImport.update({
  id: '/sallys-apparel/shop',
  path: '/sallys-apparel/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperPlusStudiosIndexRoute = SuperPlusStudiosIndexRouteImport.update({
  id: '/super-plus-studios/',
  path: '/super-plus-studios/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperPlusStudiosCustomRequestRoute =
  SuperPlusStudiosCustomRequestRouteImport.update({
    id: '/super-plus-studios/custom-request',
    path: '/super-plus-studios/custom-request',
    getParentRoute: () => rootRouteImport,
  } as any)
const SuperPlusStudiosCustomiseRoute =
  SuperPlusStudiosCustomiseRouteImport.update({
    id: '/super-plus-studios/customise',
    path: '/super-plus-studios/customise',
    getParentRoute: () => rootRouteImport,
  } as any)
const SuperPlusStudiosShopRoute = SuperPlusStudiosShopRouteImport.update({
  id: '/super-plus-studios/shop',
  path: '/super-plus-studios/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperPlusStudiosTrackRoute = SuperPlusStudiosTrackRouteImport.update({
  id: '/super-plus-studios/track',
  path: '/super-plus-studios/track',
  getParentRoute: () => rootRouteImport,
} as any)
const SafiyyrProductSlugRoute = SafiyyrProductSlugRouteImport.update({
  id: '/safiyyr/product/$slug',
  path: '/safiyyr/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SallysApparelProductSlugRoute =
  SallysApparelProductSlugRouteImport.update({
    id: '/sallys-apparel/product/$slug',
    path: '/sallys-apparel/product/$slug',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dayyah-couture/$page': typeof DayyahCouturePageRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/safiyyr/shop': typeof SafiyyrShopRoute
  '/sallys-apparel/shop': typeof SallysApparelShopRoute
  '/super-plus-studios/custom-request': typeof SuperPlusStudiosCustomRequestRoute
  '/super-plus-studios/customise': typeof SuperPlusStudiosCustomiseRoute
  '/super-plus-studios/shop': typeof SuperPlusStudiosShopRoute
  '/super-plus-studios/track': typeof SuperPlusStudiosTrackRoute
  '/dayyah-couture/': typeof DayyahCoutureIndexRoute
  '/safiyyr/': typeof SafiyyrIndexRoute
  '/sallys-apparel/': typeof SallysApparelIndexRoute
  '/super-plus-studios/': typeof SuperPlusStudiosIndexRoute
  '/safiyyr/product/$slug': typeof SafiyyrProductSlugRoute
  '/sallys-apparel/product/$slug': typeof SallysApparelProductSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dayyah-couture/$page': typeof DayyahCouturePageRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/safiyyr/shop': typeof SafiyyrShopRoute
  '/sallys-apparel/shop': typeof SallysApparelShopRoute
  '/super-plus-studios/custom-request': typeof SuperPlusStudiosCustomRequestRoute
  '/super-plus-studios/customise': typeof SuperPlusStudiosCustomiseRoute
  '/super-plus-studios/shop': typeof SuperPlusStudiosShopRoute
  '/super-plus-studios/track': typeof SuperPlusStudiosTrackRoute
  '/dayyah-couture': typeof DayyahCoutureIndexRoute
  '/safiyyr': typeof SafiyyrIndexRoute
  '/sallys-apparel': typeof SallysApparelIndexRoute
  '/super-plus-studios': typeof SuperPlusStudiosIndexRoute
  '/safiyyr/product/$slug': typeof SafiyyrProductSlugRoute
  '/sallys-apparel/product/$slug': typeof SallysApparelProductSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dayyah-couture/$page': typeof DayyahCouturePageRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/safiyyr/shop': typeof SafiyyrShopRoute
  '/sallys-apparel/shop': typeof SallysApparelShopRoute
  '/super-plus-studios/custom-request': typeof SuperPlusStudiosCustomRequestRoute
  '/super-plus-studios/customise': typeof SuperPlusStudiosCustomiseRoute
  '/super-plus-studios/shop': typeof SuperPlusStudiosShopRoute
  '/super-plus-studios/track': typeof SuperPlusStudiosTrackRoute
  '/dayyah-couture/': typeof DayyahCoutureIndexRoute
  '/safiyyr/': typeof SafiyyrIndexRoute
  '/sallys-apparel/': typeof SallysApparelIndexRoute
  '/super-plus-studios/': typeof SuperPlusStudiosIndexRoute
  '/safiyyr/product/$slug': typeof SafiyyrProductSlugRoute
  '/sallys-apparel/product/$slug': typeof SallysApparelProductSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/dayyah-couture/$page'
    | '/projects/$slug'
    | '/safiyyr/shop'
    | '/sallys-apparel/shop'
    | '/super-plus-studios/custom-request'
    | '/super-plus-studios/customise'
    | '/super-plus-studios/shop'
    | '/super-plus-studios/track'
    | '/dayyah-couture/'
    | '/safiyyr/'
    | '/sallys-apparel/'
    | '/super-plus-studios/'
    | '/safiyyr/product/$slug'
    | '/sallys-apparel/product/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/dayyah-couture/$page'
    | '/projects/$slug'
    | '/safiyyr/shop'
    | '/sallys-apparel/shop'
    | '/super-plus-studios/custom-request'
    | '/super-plus-studios/customise'
    | '/super-plus-studios/shop'
    | '/super-plus-studios/track'
    | '/dayyah-couture'
    | '/safiyyr'
    | '/sallys-apparel'
    | '/super-plus-studios'
    | '/safiyyr/product/$slug'
    | '/sallys-apparel/product/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/dayyah-couture/$page'
    | '/projects/$slug'
    | '/safiyyr/shop'
    | '/sallys-apparel/shop'
    | '/super-plus-studios/custom-request'
    | '/super-plus-studios/customise'
    | '/super-plus-studios/shop'
    | '/super-plus-studios/track'
    | '/dayyah-couture/'
    | '/safiyyr/'
    | '/sallys-apparel/'
    | '/super-plus-studios/'
    | '/safiyyr/product/$slug'
    | '/sallys-apparel/product/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DayyahCouturePageRoute: typeof DayyahCouturePageRoute
  ProjectsSlugRoute: typeof ProjectsSlugRoute
  SafiyyrShopRoute: typeof SafiyyrShopRoute
  SallysApparelShopRoute: typeof SallysApparelShopRoute
  SuperPlusStudiosCustomRequestRoute: typeof SuperPlusStudiosCustomRequestRoute
  SuperPlusStudiosCustomiseRoute: typeof SuperPlusStudiosCustomiseRoute
  SuperPlusStudiosShopRoute: typeof SuperPlusStudiosShopRoute
  SuperPlusStudiosTrackRoute: typeof SuperPlusStudiosTrackRoute
  DayyahCoutureIndexRoute: typeof DayyahCoutureIndexRoute
  SafiyyrIndexRoute: typeof SafiyyrIndexRoute
  SallysApparelIndexRoute: typeof SallysApparelIndexRoute
  SuperPlusStudiosIndexRoute: typeof SuperPlusStudiosIndexRoute
  SafiyyrProductSlugRoute: typeof SafiyyrProductSlugRoute
  SallysApparelProductSlugRoute: typeof SallysApparelProductSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dayyah-couture/': {
      id: '/dayyah-couture/'
      path: '/dayyah-couture'
      fullPath: '/dayyah-couture/'
      preLoaderRoute: typeof DayyahCoutureIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dayyah-couture/$page': {
      id: '/dayyah-couture/$page'
      path: '/dayyah-couture/$page'
      fullPath: '/dayyah-couture/$page'
      preLoaderRoute: typeof DayyahCouturePageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safiyyr/': {
      id: '/safiyyr/'
      path: '/safiyyr'
      fullPath: '/safiyyr/'
      preLoaderRoute: typeof SafiyyrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safiyyr/shop': {
      id: '/safiyyr/shop'
      path: '/safiyyr/shop'
      fullPath: '/safiyyr/shop'
      preLoaderRoute: typeof SafiyyrShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sallys-apparel/': {
      id: '/sallys-apparel/'
      path: '/sallys-apparel'
      fullPath: '/sallys-apparel/'
      preLoaderRoute: typeof SallysApparelIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sallys-apparel/shop': {
      id: '/sallys-apparel/shop'
      path: '/sallys-apparel/shop'
      fullPath: '/sallys-apparel/shop'
      preLoaderRoute: typeof SallysApparelShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-plus-studios/': {
      id: '/super-plus-studios/'
      path: '/super-plus-studios'
      fullPath: '/super-plus-studios/'
      preLoaderRoute: typeof SuperPlusStudiosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-plus-studios/custom-request': {
      id: '/super-plus-studios/custom-request'
      path: '/super-plus-studios/custom-request'
      fullPath: '/super-plus-studios/custom-request'
      preLoaderRoute: typeof SuperPlusStudiosCustomRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-plus-studios/customise': {
      id: '/super-plus-studios/customise'
      path: '/super-plus-studios/customise'
      fullPath: '/super-plus-studios/customise'
      preLoaderRoute: typeof SuperPlusStudiosCustomiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-plus-studios/shop': {
      id: '/super-plus-studios/shop'
      path: '/super-plus-studios/shop'
      fullPath: '/super-plus-studios/shop'
      preLoaderRoute: typeof SuperPlusStudiosShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-plus-studios/track': {
      id: '/super-plus-studios/track'
      path: '/super-plus-studios/track'
      fullPath: '/super-plus-studios/track'
      preLoaderRoute: typeof SuperPlusStudiosTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safiyyr/product/$slug': {
      id: '/safiyyr/product/$slug'
      path: '/safiyyr/product/$slug'
      fullPath: '/safiyyr/product/$slug'
      preLoaderRoute: typeof SafiyyrProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sallys-apparel/product/$slug': {
      id: '/sallys-apparel/product/$slug'
      path: '/sallys-apparel/product/$slug'
      fullPath: '/sallys-apparel/product/$slug'
      preLoaderRoute: typeof SallysApparelProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DayyahCouturePageRoute: DayyahCouturePageRoute,
  ProjectsSlugRoute: ProjectsSlugRoute,
  SafiyyrShopRoute: SafiyyrShopRoute,
  SallysApparelShopRoute: SallysApparelShopRoute,
  SuperPlusStudiosCustomRequestRoute: SuperPlusStudiosCustomRequestRoute,
  SuperPlusStudiosCustomiseRoute: SuperPlusStudiosCustomiseRoute,
  SuperPlusStudiosShopRoute: SuperPlusStudiosShopRoute,
  SuperPlusStudiosTrackRoute: SuperPlusStudiosTrackRoute,
  DayyahCoutureIndexRoute: DayyahCoutureIndexRoute,
  SafiyyrIndexRoute: SafiyyrIndexRoute,
  SallysApparelIndexRoute: SallysApparelIndexRoute,
  SuperPlusStudiosIndexRoute: SuperPlusStudiosIndexRoute,
  SafiyyrProductSlugRoute: SafiyyrProductSlugRoute,
  SallysApparelProductSlugRoute: SallysApparelProductSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
